### ISSUE TITLE
Crashes when opening without a file

### ISSUE THREAD

**Issue by cassidyjames** [peteruithoven/resizer#1]
When I open the app from the desktop file, I think it'd make sense to throw open an "open file" dialog since the app doesn't really work without selecting an image first.

**Comment by cassidyjames** [comment]
Alternatively, you could add a button in the UI to open an image (if an image isn't provided), it just depends on what you're thinking design-wise.

**Comment by peteruithoven** [comment]
I must admit that the app is mostly focused on working through the context menu (through the contract), I was mostly using the desktop file to test the icon. 
But yeah, in the future and to prevent confusion I should find a way to make this app useful from the Applications menu.

Maybe I'll follow [Wallpaperize](https://github.com/Philip-Scott/wallpaperize/)'s example.

**Comment by peteruithoven** [comment]
Example of how that might work: 
![frame 1](https://user-images.githubusercontent.com/523210/35619140-5165c494-067d-11e8-889e-ad14c6fe06c4.png)

If opened with image(s) the "Drop Image(s) here" could be replaced with a image preview or a generic image icon.

The above concept also makes it clearer what the "Width" and "Height" are.

**Comment by cassidyjames** [comment]
I like that! I think that's going to be required before publishing in AppCenter; right now we require apps to display in the applications menu so users can discover them. So you'll need to remove:

https://github.com/peteruithoven/resizer/blob/e34a4dc20b389c8e95f8937104c82203524a5cd7/data/com.github.peteruithoven.resizer.desktop#L10

 I'll also update the [Before You Publish](https://github.com/elementary/houston/wiki/Before-You-Publish) page on the wiki to reflect that since I realize it wasn't noted explicitly.

**Comment by peteruithoven** [comment]
This is fixed with [version 0.0.9](https://github.com/peteruithoven/resizer/releases/tag/0.9.0)
