### ISSUE TITLE
Release rejected from AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [peteruithoven/resizer#15]
Thanks for your submission! However, we currently require apps to display in the applications menu so users can discover them. So you'll need to remove:

https://github.com/peteruithoven/resizer/blob/e34a4dc20b389c8e95f8937104c82203524a5cd7/data/com.github.peteruithoven.resizer.desktop#L10

…and fix #1.

I'll also update the [Before You Publish](https://github.com/elementary/houston/wiki/Before-You-Publish) page on the wiki to reflect that since I realize it wasn't noted explicitly.

**Comment by peteruithoven** [comment]
Thanks for the review! I understand. I think there are quite a couple of apps for which opening it through the context menu makes much more sense, but I understand it from the discoverability / usability point of view. I'll work on #1.

It might also be an idea to add that to the `desktop-file-validate` checker?
