### ISSUE TITLE
Aspect ratio confusion

### ISSUE THREAD

**Issue by cjfloss** [peteruithoven/resizer#19]
So, I have an image 1920x1080 when I resize defining width as 600 and height as 500 the output image stays 600x338

The image is a png, it's a screenshot taken using the default screenshot app from elementary.

**Comment by peteruithoven** [comment]
@cjfloss thanks for trying the app. I can reproduce that with the image included below. 
Calculating `1080 / 1920 * 600 = 337.5`, so 338 seems about right? Did the resized image appear stretched in some way?

![bitmap](https://user-images.githubusercontent.com/523210/35732410-8ea52b54-0819-11e8-9918-d99f136bc1d8.png)

If you're curious, the app uses [ImageMagick's convert](https://www.imagemagick.org/script/convert.php) utility, basically executing:
```
convert /home/yourusername/bitmap.png -resize 600x500 bitmap-600x500.png
```

**Comment by cjfloss** [comment]
My comprehension of the app is that you select the image and then choose the width and the height for the new image.

So for example I want an image that is 1920x1080 to become an image with 600x500 since I'm informing the width and the height.
![screenshot from 2018-02-02 15 17 02](https://user-images.githubusercontent.com/5838486/35748278-42af7fac-082c-11e8-8a3c-7a5fe00b6c4c.png)

**Comment by peteruithoven** [comment]
I understand the confusion. But it's resized **within** the set width and height, respecting the aspect ratio. I believe it's much rarer that users want to resize something without respecting the aspect ratio. 
If you have a suggestion to better communicate this, please let me know. 
I don't really want to add extra disclaimers in the app, but I'll review the descriptions of the app.

**Comment by peteruithoven** [comment]
Alright, let's come up with some ideas on the app itself could communicate this better:
- Adding "respecting aspect ratio" disclaimer
  Explaining things with more text is bad design, people don't read. Also people might not now the term "aspect ratio".
- Add "Max" in front of labels, so it becomes "Max width" and "Max height"
  I kind of like this idea
- Adding a "Maintain aspect ratio" checkbox, making it optional. 
  People might not know the term and I find the feature of resizing without maintaining the ratio mostly useless.
- Visually showing width and height "rulers". See example below where image wouldn't fill the whole height. 
![frame 2](https://user-images.githubusercontent.com/523210/35766452-63e2e242-08d9-11e8-9e8e-db68179487a4.png)

**Comment by peteruithoven** [comment]
What it looks like at the moment with some textual clarifications:
![screenshot from 2018-09-14 19-33-23](https://user-images.githubusercontent.com/523210/45565818-20fd4400-b855-11e8-982f-39f7f599d77a.png)
