### ISSUE TITLE
Improve icons

### ISSUE THREAD

**Issue by peteruithoven** [peteruithoven/resizer#2]
Currently I've simply reused the picture from the [multimedia-photo-manager.svg](https://github.com/elementary/icons/blob/master/apps/128/multimedia-photo-manager.svg) icon, but it's blue part is quite dark causing there not being enough contract between the arrow and the picture. 

Current icon (64px):
![resizer-64 svg](https://user-images.githubusercontent.com/523210/35727233-b8b6b5aa-0807-11e8-8446-622c52a4549e.png)
[resizer-64.svg.zip](https://github.com/peteruithoven/resizer/files/1688847/resizer-64.svg.zip)

**Comment by cassidyjames** [comment]
@TraumaD? :wink:

**Comment by TraumaD** [comment]
👀

**Comment by TraumaD** [comment]
![resizer2](https://user-images.githubusercontent.com/10608836/35717523-53022896-07a5-11e8-9ece-ea824785fe90.png)
Thoughts?

**Comment by peteruithoven** [comment]
Like! Also better communicates that users will usually resize to smaller.
Could you share the svg, I'd love to try some other colors, I'm not sure about that purple, I'd like to try yellow/orange, green or something blackish. 

You did inspire me to try other colors and alter the existing icon to:
![resizer-64 svg](https://user-images.githubusercontent.com/523210/35727080-3a5be946-0807-11e8-9184-e6250594db37.png)
[resizer-64.svg.zip](https://github.com/peteruithoven/resizer/files/1688841/resizer-64.svg.zip)

**Comment by TraumaD** [comment]
I did a grid of the icon with all the colours in the elementary palette. Here's what they look like:
![resizer-colours-preview](https://user-images.githubusercontent.com/10608836/35739169-5b6a19de-07f6-11e8-822a-4bdbd85b5a1c.png)

I only have the 64px version of the icon done for now here it is:
[resizer-64-icon.zip](https://github.com/peteruithoven/resizer/files/1689745/resizer-64-icon.zip)

**Comment by TraumaD** [comment]
I think I personally like the yellow or purple the best. The red makes it feel like a destructive action, the blue and green kinda blend into the rest of the icon, and the dark ones just don't show up super well on dark backgrounds. So if the user had the app in plank with a dark desktop background the arrows would get harder to make out.

**Comment by peteruithoven** [comment]
@TraumaD thanks for all that work, but I'd really like to keep using the same picture, I like how it's the same picture that's used in other photo related icons in elementary OS. 

I think I'll try replacing the picture in the icons you've created, because I think the opaque big and smaller picture and the yellow color are great ideas. 

I've simplified the icon file paths, using Meson to rename them during installation, that should make working on them easier, see: 
https://github.com/peteruithoven/resizer/commit/4db8a7cb1e96b59798f2fbd5e349114b40670e93
https://github.com/elementary/website/issues/1885#issuecomment-364514302

**Comment by TraumaD** [comment]
@peteruithoven Are you wanting that darker yellow like you have in the icon you made above or the lighter yellow like the icon I have there? I don't mind fixin them up real quick.

**Comment by peteruithoven** [comment]
I didn't want to ask, but that would be really great. I'm still quite slow with Inkscape. I guess which one works better, contrast wise, as long as it follows the elementary OS's [Color Palette](https://elementary.io/docs/human-interface-guidelines#color).

**Comment by TraumaD** [comment]
It's no problem. I'm almost done. I'll update my PR soon.

**Comment by TraumaD** [comment]
Thoughts?

![resizer_colours](https://user-images.githubusercontent.com/10608836/36046461-9c085e08-0d9e-11e8-8713-e4a8c08ab808.png)

**Comment by peteruithoven** [comment]
The third one is going to much towards red I think, which is like you said linked to "destructive actions".
I like the second one the most. Mostly visually, because it matches the sand. Even though the first one might have better contrast.

**Comment by TraumaD** [comment]
For some more context you can look at the smallest icon where the contrast is going to be most important in making discernible shapes.

![resizer_colours_16](https://user-images.githubusercontent.com/10608836/36047190-f5324bae-0da0-11e8-8a50-3a3ead592036.png)

**Comment by TraumaD** [comment]
The red-orange colour was chosen because it matches the starfish. But yeah colours close to red can carry a destructive connotation. The darker one that matches the sand I think gets a little muddy at the small sizes. Idk 🤷‍

**Comment by peteruithoven** [comment]
That's... indeed problematic, how it's  blends into the sand... Do you think we should try the silver maybe? 

![resizer-silver-on-black-64 svg](https://user-images.githubusercontent.com/523210/36048044-362731dc-0dde-11e8-95ba-1e89d5f6114e.png)
![resizer-silver-64 svg](https://user-images.githubusercontent.com/523210/36048046-364faf68-0dde-11e8-8533-8ffb818d62ec.png)

**Comment by TraumaD** [comment]
Silver could work.
![16_lite](https://user-images.githubusercontent.com/10608836/36048634-7b51aa5a-0da5-11e8-91da-16e516d43d2a.png) ![16_dark](https://user-images.githubusercontent.com/10608836/36048637-7d57f5ac-0da5-11e8-8bef-1fb7faded93e.png)
![64_lite](https://user-images.githubusercontent.com/10608836/36048613-6ee211ec-0da5-11e8-8eb9-24aa678db3f6.png) ![64_dark](https://user-images.githubusercontent.com/10608836/36048616-7053a8f6-0da5-11e8-94df-8a1082440b65.png)

**Comment by peteruithoven** [comment]
I like it :)

**Comment by TraumaD** [comment]
Cool, I updated the PR.
