### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by peteruithoven** [peteruithoven/resizer#3]
I'd love to add translations, but I haven't been able to figure out how. The current elementary developer documentation [on translations](https://elementary.io/docs/code/getting-started#Adding-Translations) isn't switched to Meson [yet](https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e).

I found the following Meson guide: http://mesonbuild.com/Localisation.html
One of the steps I haven't figured out is creating the .po files, to quote the above guide:
> Meson does not currently have built in commands for generating po files from the pot file. This is because translations are usually done by people who are not developers and thus have their own workflows.

**Comment by peteruithoven** [comment]
Daniel gave the following instructions on Slack:

> To generate po files you need to:
> 1. Have all your source files listed in POTFILES
> 2. Have all the languages you want listed in LINGUAS
> 3. `meson build --prefix=/usr`, `cd build`, `ninja com.github.your-app-pot`, `ninja com.github.your-app-update-po`

**Comment by peteruithoven** [comment]
Worked: https://github.com/peteruithoven/resizer/commit/9cf261e88cfdfc3cafde82f4282d7f0947044577

**Comment by peteruithoven** [comment]
To test this I added Dutch translations: https://github.com/peteruithoven/resizer/commit/8341db0f7d9afef8f74b214d9b513a2e2dd1aac1
But after changing my system to Dutch, doing a rebuild (`ninja`), logging out, logging in, the app still shows the original English text.

```
$ locale
LANG=nl_NL.UTF-8
LANGUAGE=nl_NL
LC_CTYPE="nl_NL.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="nl_NL.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="nl_NL.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

**Comment by NathanBnm** [comment]
@peteruithoven  is ths issue still valable ? Maybe you have to close it

**Comment by peteruithoven** [comment]
Good point, I've received a couple of translations in the mean time, but I haven't seen the app translated for myself.
There should be translations for French, Dutch, and Lithuanian.
