### ISSUE TITLE
How can I translate 'Resize images'?

### ISSUE THREAD

**Issue by michalzkosmosu** [peteruithoven/resizer#46]
How can I translate 'Resize images' from context menu into Polish?
![](https://i.postimg.cc/Gp6kLbP8/optimize-resize.gif)

**Comment by peteruithoven** [comment]
I'm pretty sure it's this string: 
https://github.com/peteruithoven/resizer/blob/2067abf21ad304f9d52f06e1a02ac02087abfbcb/data/com.github.peteruithoven.resizer.contract#L2

**Comment by NathanBnm** [comment]
The contract file hasn't been included into translation for now.

**Comment by peteruithoven** [comment]
I'm going to close this, as we can't add this item to the files context menu anymore anyway.
