### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by NathanBnm** [peteruithoven/resizer#47]
French translation update (10 months ago) weren't pushed into a new release. Could you please create a new release? (Maybe check the pull requests before)

**Comment by peteruithoven** [comment]
Please understand that's it's quite some work. And I usually run into issues like:
https://travis-ci.org/peteruithoven/resizer/builds/650917536?utm_medium=notification&utm_source=email

**Comment by NathanBnm** [comment]
It seems that Houston CI is broken with some repos. It's not the first time I see this error.

**Comment by peteruithoven** [comment]
I think I figured it out: https://github.com/peteruithoven/resizer/issues/48https://github.com/peteruithoven/resizer/issues/48 

I've now submitted a new version for review.

**Comment by peteruithoven** [comment]
It's been approved & released :)
