### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danrabbit** [peteruithoven/resizer#50]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by peteruithoven** [comment]
I'm trying to build for flatpak, following: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging

I'm running into this error:
> ../meson.build:24:0: ERROR: File build/config.vala does not exist.

This `build/config.vala` is generated dynamically using meson:
https://github.com/peteruithoven/resizer/blob/master/meson.build#L12-L20
It creates this file with a constant with the project name, which enables me to get the project name in vala. 

It looks like flatpak uses a different build folder. 

I've tried using `meson.current_build_dir()+'/config.vala'` instead but then I'm getting this error:
> cc: error: com.github.peteruithoven.resizer.p/config.c: No such file or directory

I can't use `rename` in `configure_file`. 
I also can't specify a sub directory in `configure_file`'s `output`.

**Comment by peteruithoven** [comment]
Ah I found an example in the onboarding repo. This works by storing the result of configure_file in a var and passing that to executable. Very neat.
https://github.com/elementary/onboarding/blob/35167360de3b130b2483d06b8d6712403c4a3143/src/meson.build#L23-L33

**Comment by peteruithoven** [comment]
This might take a while.

I'll need to figure out how to 
- Reproduce the white Drop your Image(s) here panel
- Remove the headerbar
- Get access to drop files
- Arguably the most important: how to make it available through the right click menu in Files, which I've normally achieved by adding a contract file. 

![Screenshot from 2021-07-25 21-55-59@2x](https://user-images.githubusercontent.com/523210/126911793-7cbaf335-2f6a-47ca-a5fa-08265af7ba40.png)

It is very cool that I can create this flatpak version for version 6 from version 5.
