### ISSUE TITLE
Doesn't work on elementary OS 6 Beta (There was an issue resizing...)

### ISSUE THREAD

**Issue by wout** [peteruithoven/resizer#51]
**Describe the bug**
Unable to resize images from the contextual menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Resize any image from the contextual menu
2. An error is shown (There was an issue resizing...)

**Desktop (please complete the following information):**
 - OS: elementary OS
 - OS Version: 6 Beta 
 - Built from source

**Additional context**
From the syslog:

```
Jul 24 14:54:27 Rossy gala[1835]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
Jul 24 14:54:27 Rossy gala[1835]: invalid (NULL) pointer instance
Jul 24 14:54:27 Rossy gala[1835]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Jul 24 14:54:33 Rossy org.elementary.Contractor[322323]: resizing: /home/wout/Downloads/IMG_20210724_145017.jpg
Jul 24 14:54:33 Rossy org.elementary.Contractor[322323]: adding message: There was an issue resizing '/home/wout/Downloads/IMG_20210724_145017.jpg'
```

**Comment by peteruithoven** [comment]
Interesting. I've yet to run version 6, issues with virtual machines etc. Good to know there will be some kind of issue getting it to work at all on version 6.

**Comment by wout** [comment]
I love this little app and use it a lot. So I'm happy to help you our debugging this.

**Comment by peteruithoven** [comment]
Finally fixed my virtual box issue :) 

(I installed the elementary SDK, cloned this repo, build and installed the app)

I ran the application with debugging enabled, see: [debug logs](https://elementary.io/docs/code/os-dev#debug-logs)
```
G_MESSAGES_DEBUG=all ./com.github.peteruithoven.resizer
```

This showed which command is used to resize images
```
convert /home/peteruithoven/Pictures/examples/Tj Holowaychuk.jpg -resize 1000x1000> /home/peteruithoven/Pictures/examples/Tj Holowaychuk-1000.jpg
```

Trying to run this showed
```
 convert /home/peteruithoven/Pictures/examples/Tj Holowaychuk.jpg -resize 1000x1000> /home/peteruithoven/Pictures/examples/Tj Holowaychuk-1000.jpg

Command 'convert' not found, but can be installed with:

sudo apt install imagemagick-6.q16                  # version 8:6.9.10.23+dfsg-2.1ubuntu11.4, or
sudo apt install imagemagick-6.q16hdri              # version 8:6.9.10.23+dfsg-2.1ubuntu11.4
sudo apt install graphicsmagick-imagemagick-compat  # version 1.4+really1.3.35-1
```

So maybe imagemagick's convert dependency needs to be listed as a dependency in a different manner for elementary OS 6?

**Comment by peteruithoven** [comment]
Hey cool, small world, we've crossed paths before
https://github.com/svgdotjs/svg.js/issues?q=commenter%3Apeteruithoven

**Comment by peteruithoven** [comment]
Simple workaround for now is manually installing `imagemagick`.

**Comment by peteruithoven** [comment]
While this would probably only clarify things for people building from source, I would like to declare imagemagick as a dependency in `meson.build`. 

For some reason I can't simply add `dependency('imagemagick')` to the `dependencies` list of `executable`. 

Apt search confirms I have imagemagick installed:
```
imagemagick/focal-updates,now 8:6.9.10.23+dfsg-2.1ubuntu11.4 amd64 [installed]
  image manipulation programs -- binaries
```
But when running `meson build --prefix=/usr` I get:
```
Run-time dependency imagemagick found: NO (tried pkgconfig)

meson.build:22:0: ERROR: Dependency "imagemagick" not found, tried pkgconfig
```

imagemagick is not available through pkgconfig maybe?

[Meson's Dependencies docs](https://mesonbuild.com/Dependencies.html) mentions:
> Unfortunately several packages don't provide pkg-config files

I'm now looking into:
https://mesonbuild.com/Dependencies.html#dependencies-with-custom-lookup-functionality

Kind of out of my depth, so help is more than welcome.

**Comment by wout** [comment]
> Hey cool, small world, we've crossed paths before

Small world indeed! I thought I recognised your name. :nerd_face:

> Simple workaround for now is manually installing `imagemagick`

Yes, that worked, thanks. I'm not really familiar with writing and building Linux apps. I've just built it from source because the app wasn't available from the AppStore or Flathub, and I really needed it.

ImageMagick simply wasn't installed on my system, so that was a quick and easy fix. Thanks again for the super quick intervention.

**Comment by peteruithoven** [comment]
I've got a tip on their matrix chat, that I might be able to use `find_program("convert")`, but if I use that in the dependency list:
```
executable(
    ...,
    dependencies: [
        ...
        find_program('convert')
    ],
```
It does find the program, but fails:
> Program convert found: YES (/usr/bin/convert)
> 
> meson.build:22:0: ERROR: Argument is of an unacceptable type 'ExternalProgram'.
Must be either an external dependency (returned by find_library() or dependency()) or an internal dependency (returned by declare_dependency())

**Comment by peteruithoven** [comment]
Just including `find_program('convert')` on a line on it's own works. But adding a runtime check with a readable error is actually a better solution. That would also cover other cases. (It should be really rare, if we switch to Flatpak though?)

**Comment by wout** [comment]
> It should be really rare, if we switch to Flatpak though?

Not sure, but thanks for the fix!
