### ISSUE TITLE
AppCenter brand colors are low contrast

### ISSUE THREAD

**Issue by danrabbit** [peteruithoven/resizer#63]
**Describe the bug**

While reviewing your app I noticed that the brand colors used in AppCenter only have a contrast ratio of 1.9:1. The bare minimum A level contrast ratio is 3:1

![Screenshot from 2021-09-09 12 20 47](https://user-images.githubusercontent.com/7277719/132749681-0d4a9375-5cc0-45ea-8979-b1998437e778.png)

**Expected behavior**

I would recommend shooting for AA level to maximize legibility for the most amount of people. You could do this a couple ways. One is by changing the foreground color to something like `#00526E`

![Screenshot from 2021-09-09 12 24 31](https://user-images.githubusercontent.com/7277719/132750035-c20c344b-7fd9-4dbc-ae23-54dfebb3fca0.png)

or even darker for AAA like `#003254`:

![Screenshot from 2021-09-09 12 29 55](https://user-images.githubusercontent.com/7277719/132750592-fbe6b5a5-c70b-4ec6-a2b5-97f6311a2788.png)

Or you could go the other way around and make the background darker like maybe `#007CBF`. I've also shifted the hue a bit here to try to get a little bit higher of a brightness value:

![Screenshot from 2021-09-09 12 26 55](https://user-images.githubusercontent.com/7277719/132750243-f9b3371a-f3de-4e7d-8372-a7833ac48b7c.png)

**Comment by peteruithoven** [comment]
Thanks for the thorough advice!
