### ISSUE TITLE
Installing from appcenter gives a much older version of the app

### ISSUE THREAD

**Issue by adithyankv** [peteruithoven/resizer#79]
**Describe the bug**
Installing `Resizer` from the appcenter seems to install a version much older than the latest release. The `flatpak list` command shows
```
Resizer                          com.github.peteruithoven.resizer           2.0.3                      stable           appcenter         user
```

**To Reproduce**
Install `Resizer` directly from appcenter.

**Expected behavior**
The latest version of resizer should be installed

**Screenshots**
![Screenshot from 2022-01-13 23-47-33](https://user-images.githubusercontent.com/29067795/149427501-04d6293a-afe9-423a-9891-c350ffea7570.png)
The screenshots on appcenter seem to be for the latest release however the "What's new" section seems to be showing the older release in question.
![Screenshot from 2022-01-14 00-07-04](https://user-images.githubusercontent.com/29067795/149428406-2f274fa0-de43-4654-84eb-66d7a19917fa.png)

**Desktop:**
 - OS: elementary OS
 - OS version: 6.1 Jólnir

**Comment by peteruithoven** [comment]
Maybe because they switched how they're publishing apps to the AppCenter. I'll need to figure out how to submit with the new system. 
I guess a Pull request to  
https://github.com/elementary/appcenter-reviews#submitting-an-app

**Comment by peteruithoven** [comment]
Got a review from Danielle and it seems to be published now :)
